Added implementations of functions: createGetter, invertObj, trimSymbols, uniq
js-tasks-ru/js-20220209_evstifeevmaksim pull request #3
Opened 2022-02-18 07:52 UTC by m-evstifeev

2022-02-18 07:53 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-02-19 10:40 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    const pathKeys = path.split(".");
было бы неплохо вынести `path.split('.')` в родительскую функцию, иначе данная операция будет выполняться каждый раз при вызове геттера, хотя данное значение требуется рассчитать только один раз при создании геттера

2022-02-19 10:40 UTC, dosandk requested changes
👍 good 
решение `createGetter` следует поправить

2022-02-19 13:36 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-02-19 16:26 UTC, dosandk approved these changes
👍 good

2022-02-19 16:27 UTC, merged